language: python

python:
#  - "2.6" << misses pysam 'import sysconfig' => 'ImportError: No module named sysconfig'
  - "2.7"

# Needs FuMa, which needs HTSeq ported to Py3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

install:
  - pip install flake8
  - virtualenv -p python2 .venv_pysam_0_9 ; source .venv_pysam_0_9/bin/activate ; pip install pysam==0.9 ; pip install -r requirements.txt ; python setup.py install ; pip install flake8 ; deactivate
  - virtualenv -p python2 .venv_pysam_0_10 ; source .venv_pysam_0_10/bin/activate ; pip install pysam==0.10 ; pip install -r requirements.txt ; python setup.py install ; pip install flake8 ; deactivate

script:
  - command -v dr-disco
  - source .venv_pysam_0_9/bin/activate ; python -c 'import pysam; print (pysam.__version__)' ; nosetests -v tests/*.py ; deactivate
  - source .venv_pysam_0_10/bin/activate ; python -c 'import pysam; print (pysam.__version__)' ;nosetests -v tests/*.py ; deactivate
  - cd "$TRAVIS_BUILD_DIR" && pip install flake8 && flake8 --exclude=.git --ignore=E501 .

notifications:
  email: false
