language: python

python:
#  - "2.6" << misses pysam 'import sysconfig' => 'ImportError: No module named sysconfig'
  - "2.7"

# Needs FuMa, which needs HTSeq ported to Py3
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev

install:
  - pip install -r requirements.txt

script:
  - nosetests -v tests/*.py

notifications:
  email: false
